### ISSUE TITLE
[Question] What is the motivation for using the terms "grains" in `client.sls`

### ISSUE THREAD

**Issue by jzandbergen** [tcpcloud/salt-formula-collectd#55]
Hi All,

I'm currently studying the "meta" pattern as seen in client.sls. 
And I am wondering; "What is the motivation for using the term "grains" in [client.sls](https://github.com/salt-formulas/salt-formula-collectd/blob/master/collectd/client.sls#L15-L24)?

This because I couldn't see the relation with "salt grains". My colleague suggested it might be chosen in  a complete different context. Any clarification would be appreciated.

Cheers!

**Comment by cznewt** [comment]
Hello @jzandbergen ,
it has been while I checked this code, took me a little while to dedust the memories, this is a quite deep dive question. 

The term "grains" really means salt grains in the example, let me explain. Each service may have defined [extra metadata](https://github.com/salt-formulas/salt-formula-collectd/tree/master/collectd/meta) which is yaml fragment of configuration/model for that service. Here collectd client goes over pillar, checks what is installed and whether collectd meta fragment is present. All these service meta fragments are then serialized into salt grain data structure.

This grain(s)  (as there may be more for each meta service) are then regularly pushed to master by the "Salt Mine" means. Now we have all the meta of all services on master. This we can reuse at some other places to construct things like live infra docs or remote monitoring checks/probes.

I sometimes miss this pattern, with Kube and annotation/label strings solving meta, it was like going back to medieval  :smile:

**Comment by jzandbergen** [comment]
Hi @cznewt ,

I see, i was missing the salt mine part. Thank you very much for your detailed explanation.
